spring.application.name=ecommerce-app

# 🌐 Configuration de la connexion à la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root

# ⚙️ Configuration de l'ORM (Hibernate/JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-null-for-primitives=false