spring.application.name=ecommerce-app

# 🌐 Configuration de la connexion à la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root

# ⚙️ Configuration de l'ORM (Hibernate/JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-null-for-primitives=false

# Augmenter la taille maximale des fichiers uploadés
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#partie AI ................................
# Configuration de Spring AI pour utiliser OpenRouter
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=

# Modèle gratuit supportant le Function Calling (ex: Llama 3.3 70B ou Gemini Flash)
spring.ai.openai.chat.options.model=inclusionai/ling-3.0-flash-vl:free
spring.ai.openai.chat.options.temperature=0.3